<div id="chart-perf"></div>

<?php if ($this->graphType != 'Scatter'):?>
<div id="chart-avail"></div>
<?php endif; ?>

<script src="http://code.highcharts.com/highcharts.js"></script>
<script type="text/javascript">
     $(function () {
         $('#chart-perf').highcharts({
         chart: {
             type: '<?php echo $this->hcGraphType ?>',
             height: 295,
             reflow: true,
             zoomType: 'xy'
         },

         legend: false,

         title: {
             text: '<?php echo $this->title ?>'
         },

         xAxis: {
             <?php if ($this->hcGraphType != 'bar' ): ?>
             tickInterval: <?php echo $this->step ?>,
             <?php endif ; ?>
             categories: <?php echo $this->xTime ?>,
             labels: {
                 rotation: 0,
                 y: <?php echo $this->y ?>
             },
             title:{
                 text: '<?php echo $this->graphType ?>'
             }
         },

         yAxis: {
             min: 0,
             title: {
                 text: '<?php echo $this->pageComponent ?>'
             }
         },

         tooltip: {
             formatter: function() {
                 return '<b>' + this.x + '</b><br/>' + this.series.name + ': ' + this.y + ' <?php echo $this->gUnit ?><br/>Error Code: ' + this.point.errorCode;
             }
         },

         plotOptions: {
             area: {
                 marker: {
                     enabled: false,
                     symbol: 'circle',
                     radius: 2,
                     states: {
                         hover: {
                             enabled: true
                         }
                     }
                 }
             }
         },

         series: [{
                 name: '<?php echo $this->pageComponent ?>',
                 data: <?php echo $this->perfDataPoints ?>
         }]
         })
     });

     <?php if ($this->graphType != 'Scatter'):?>
     $(function () {
         $('#chart-avail').highcharts({
         chart: {
             type: '<?php echo $this->hcGraphType ?>',
             height: 295,
             reflow: true,
             zoomType: 'xy'

         },

         legend: false,

         title: {
             text: '<?php echo $this->graphType ?> Graph'
         },

         xAxis: {
             <?php if ($this->hcGraphType != 'bar' ): ?>
             tickInterval: <?php echo $this->step ?>,
             <?php endif ; ?>
             categories: <?php echo $this->xTime ?>,
             labels: {
                 rotation: 0,
                 y: <?php echo $this->y ?>
             },
             title:{
                 text: '<?php echo $this->graphType ?>'
             }
         },

         yAxis: {
             min: 0,
             max: 100,
             title: {
                 text: 'Availability (%)'
             }
         },

         tooltip: {
             formatter: function() {
                 return '<b>' + this.x + '</b><br/>' + this.series.name + ': ' + this.y + '%';
             }
         },

         plotOptions: {
             area: {
                 marker: {
                     enabled: false,
                     symbol: 'circle',
                     radius: 2,
                     states: {
                         hover: {
                             enabled: true
                         }
                     }
                 }
             }
         },

         series: [{
                 name: 'Availability',
                 data: <?php echo $this->availDataPoints ?>,
                 color: '#89854E'
         }]
         })
     });
     <?php endif; ?>
</script>
