<?php
$graph = $this->graphData;

switch ($this->graphType) {
    case 'Scatter':
        $hcGraphType = 'scatter';
        $rotation = 0;
        $step = 8;
        $y = 15;
        $title = 'Scatter Plot';
        foreach ($graph->list as $datapoint) {
            foreach ($datapoint->children() as $dp) {
                $t = date('D H:i:s', strtotime($dp->datetime));
                $time[] = $t;
                $perfData[] = array($t, (string)$dp->txn__summary->delta__msec / 1000);
            }
        }
        break;

    case 'Time':
        $hcGraphType = 'area';
        $rotation = 0;
        $step = (3 * $this->days) / 86400;
        $y = 15;
        $title = $graph->measurement->alias;
        foreach ($graph->measurement->bucket_data as $datapoint) {
            foreach ($datapoint as $dp) {
                $t = date('D H:i:s', strtotime($dp['name']));
                $time[] = $t;
                $perfData[] = array($t, (string)$dp->perf_data['value']);
                $availData[] = array($t, (string)$dp->avail_data['value']);
            }
        }
        break;

    case 'Agent':
    case 'Backbone':
    case 'City':
    case 'Country':
    case 'Region':
        $hcGraphType = 'bar';
        $rotation = 0;
        $step = 0;
        $y = 0;
        $title = $graph->measurement->alias;
        foreach ($graph->measurement->bucket_data as $datapoint) {
            foreach ($datapoint as $dp) {
                $t = (string)$dp['name'];
                $time[] = $t;
                $perfData[] = array($t, (string)$dp->perf_data['value']);
                $availData[] = array($t, (string)$dp->avail_data['value']);

            }
            break;
        }
}

$xTime = json_encode($time);
$perfDataPoints = json_encode($perfData, JSON_NUMERIC_CHECK);

if ($this->graphType != 'Scatter') {
    $availDataPoints = json_encode($availData, JSON_NUMERIC_CHECK);
}
?>
<div id="chart-perf"></div>

<?php if ($this->graphType != 'Scatter'):?>
<div id="chart-avail"></div>
<?php endif; ?>

<script src="http://code.highcharts.com/highcharts.js"></script>
<script type="text/javascript">
     var chart = new Highcharts.Chart({
         chart: {
             renderTo: 'chart-perf',
             type: '<?php echo $hcGraphType ?>',
             height: 295,
             reflow: true
         },

         legend: false,

         title: {
             text: '<?php echo $title ?>'
         },

         xAxis: {
             <?php if ($hcGraphType != 'bar' ): ?>
             tickInterval: <?php echo $step ?>,
             <?php endif ; ?>
             categories: <?php echo $xTime ?>,
             labels: {
                 rotation: <?php echo $rotation ?>,
                 y: <?php echo $y ?>
             },
             title:{
                 text: '<?php echo $this->graphType ?>'
             }
         },

         yAxis: {
             min: 0,
             title: {
                 text: 'Performance (seconds)'
             }
         },

         tooltip: {
             formatter: function() {
                 return '<b>' + this.x + '</b><br/>' + this.series.name + ': ' + this.y + ' s';
             }
         },

         series: [
             {
                 name: 'Performance',
                 data: <?php echo $perfDataPoints ?>
             }
         ]

     });

     <?php if ($this->graphType != 'Scatter'):?>
     var chart = new Highcharts.Chart({
         chart: {
             renderTo: 'chart-avail',
             type: '<?php echo $hcGraphType ?>',
             height: 295,
             reflow: true
         },

         legend: false,

         title: {
             text: '<?php echo $this->graphType ?> Graph'
         },

         xAxis: {
             <?php if ($hcGraphType != 'bar' ): ?>
             tickInterval: <?php echo $step ?>,
             <?php endif ; ?>
             categories: <?php echo $xTime ?>,
             labels: {
                 rotation: <?php echo $rotation ?>,
                 y: <?php echo $y ?>
             },
             title:{
                 text: '<?php echo $this->graphType ?>'
             }
         },

         yAxis: {
             min: 0,
             max: 100,
             title: {
                 text: 'Availability (%)'
             }
         },

         tooltip: {
             formatter: function() {
                 return '<b>' + this.x + '</b><br/>' + this.series.name + ': ' + this.y + '%';
             }
         },

         series: [
             {
                 name: 'Performance',
                 data: <?php echo $availDataPoints ?>,
                 color: '#89854E'
             }
         ]

     });
     <?php endif; ?>
</script>
