
<div class="debugController">
  <h3>User:</h3>
  <p><?php echo$this->user ?></p>
  <h3>Role:</h3>
  <p><?php echo $this->role ?></p>

  <h3>Result:</h3>
  <table class="acl">
  <tr>
  <th>Access</th>
  <th>Resource</th>
  <th>Permission</th>
  </tr>
  <?php
  foreach ($this->allowed as $resource => $access) {
      echo '<tr><td>' . $access. '</td>' . $resource .'</tr>';
  }
  ?>
  </table>
</div>
