<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Keynote API - Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="/bootstrap/css/custom.css" rel="stylesheet">
    <link rel="shortcut icon" href="/images/favicon.ico">  
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="/js/widget.js"></script>
  </head>
  <body>
    <?php echo $this->render('navbar.phtml') ?>

    <!-- Container -->
    <div class="container" id="sortable">

      <?php echo $this->layout()->content ?>

      <hr class="featurette-divider">

      <footer>
        <p>&copy; Keynote Systems, Inc. 2013</p>
      </footer>

    </div>
    <!-- /container -->
  </body>
</html>