    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="/daily/index/product/ApP">ApP Daily Report</a></li>
                  <li><a href="/daily/index/product/MWP">MWP Daily Report</a></li>
                  <li><a href="/daily/index/product/TxP">TxP Daily Report</a></li>
                  <li class="divider"></li>
                  <li><a href="/report">Slot/Alarm Report</a></li>
                  <li><a href="/abc">Automatic Brick Creator</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dashboards <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="/dashboard">NOC Style Dashboard</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Graphs <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="/graph">Graph Creator</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-text pull-right">
              <?php echo date_default_timezone_get() . ' ' . date('H:i A')?>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
