
<!-- Custom start -->
<table width="600" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td valign="top" align="center" class="contenttbl-b">
                <table width="568" cellpadding="0" cellspacing="0">
                    <tbody>
                        <tr height="16">
                            <td></td>
                        </tr>
                        <tr>
                            <!-- Content start -->
                            <td valign="top" align="left">
                                    <div class="h"><?php echo $this->customHeadline ?></div>
                                    <div><?php echo $this->customMessage ?></div>
                            </td>
                            <!-- Content end -->
                        </tr>
                        <tr height="16">
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr height="8">
            <td></td>
        </tr>
    </tbody>
</table>
<!-- Custom end -->
