
<table width="600" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td width="550" valign="top" align="center" class="contenttbl">
				<table width="518" cellpadding="0" cellspacing="0">
					<tbody>
						<tr height="8">
							<td></td>
						</tr>
						<tr height="46">
							<!-- Content start -->
							<td valign="top" align="left">
							    <div>
									<?php echo $this->translate('prepared') . ' ' . $this->fullName ?>
							    </div>
								<div>
									<strong>Email: <a href="mailto:<?php echo $this->mailFrom ?>"><?php echo $this->mailFrom ?>
									</a>
									</strong>
								</div>
								<div>
									<strong><a href="http://www.keynote.com">http://www.keynote.com</a>
									</strong>
								</div>
								<div>
									<em>Copyright &copy; 2013 Keynote Systems, Inc., All rights reserved.</em>
								</div>
							</td>
							<!-- Content end -->
						</tr>
						<tr height="8">
							<td></td>
						</tr>
					</tbody>
				</table>
			</td>
			<td width="8">&nbsp;</td>
			<td width="50" valign="top" align="center">
				<table width="50" cellpadding="0" cellspacing="0">
					<tbody>
						<tr height="50">
							<td width="50" align="center" class="contenttbl">
							    <a href="https://twitter.com/keynotesystems"><img src="http://castley.co.uk/images/twitter-small.png" alt="" title="" width="32" height="32" border="0" style="max-width: 32px; max-height: 32px;" /></a>
							</td>
						</tr>
						<tr height="8">
							<td colspan="5"></td>
						</tr>
						<tr height="50">
							<td width="50" align="center" class="contenttbl"><a href="http://www.keynote.com"><img src="http://castley.co.uk/images/logo-small.png" alt="" title="" width="32" height="32" border="0" style="max-width: 32px; max-height: 32px;" /></a>
						</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
