
<!-- Logo start -->
<table width="600" cellpadding="0" cellspacing="0">
    <tbody>
        <tr height="8">
            <td colspan="2"></td>
        </tr>
        <tr>
            <td valign="bottom" align="left">
                <img src="http://download.keynote.com/images/logo.gif" width="279" height="70" border="0" title="" alt="Keynote Logo" />
            </td>
            <td valign="bottom" align="right">
                <div class="small" style="color: #333333"><?php echo date('l, jS F Y')?></div>
            </td>
        </tr>
        <tr height="8">
            <td colspan="2"></td>
        </tr>
    </tbody>
</table>
<!-- Logo end -->

<!-- Intro start -->
<table width="600" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td valign="top" align="center" class="contenttbl">
                <table width="568" cellpadding="0" cellspacing="0">
                    <tbody>
                        <tr height="16">
                            <td></td>
                        </tr>
                        <tr>
                            <!-- Content start -->
                            <td valign="top" align="left">
                                <div class="h-small" style="color: #FFFFFF"><?php echo $this->translate('userexp1', abs(number_format($this->avgPerf - 2, 2)), $this->fastSlow) ?></div>
                            </td>
                            <!-- Content end -->
                        </tr>
                        <tr height="16">
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr height="8">
            <td></td>
        </tr>
    </tbody>
</table>
<!-- Intro end -->
