
<!-- Greeting start -->
<table width="264" cellpadding="0" cellspacing="0">
    <tbody>
        <tr height="16">
            <td></td>
        </tr>
        <tr>
            <!-- CONTENT start -->
            <td valign="top" align="left">
                <div>
                <strong><?php echo $this->greeting ?> </strong>
                <p>
                <?php echo $this->translate('intro1', $this->url, $this->agentCount) ?>
                </p>
                <p>
                <?php echo $this->translate('intro2', $this->interval, $this->product, $this->browserDevice, $this->days) ?>
                </p>
                <p>
                <?php echo $this->translate('intro3') ?>
                </p>
                </div>
            </td>
            <!-- CONTENT end -->
        </tr>
        <tr height="16">
            <td></td>
        </tr>
    </tbody>
</table>
<!-- Greeting end -->
