<form class="form-horizontal" method="post" action="save">
 <fieldset>
    <legend>Enter API Key</legend>
    <div class="row">
    <div class="span5">
    <div class="control-group">
    <label class="control-label" for="mailFrom">Your Name</label>
    <div class="controls">
      <input class="span2" type="text" id="mailFrom" name="mailFrom" placeholder="Barney Rubble">
    </div>
  </div>
  </div>
  <div class="span4">
  <div class="control-group">
    <label class="control-label" for="mailTo">Your E-Mail Address</label>
    <div class="controls">
      <input type="text" id="mailTo" name="mailTo" placeholder="someone@acme.com">
    </div>
  </div>
  </div>
  </div>
  <div class="row">
  <div class="span5">
  <div class="control-group">
    <label class="control-label" for="api_key">API Key</label>
    <div class="controls">
      <input type="text" id="api_key" name="api_key" placeholder="abc123">
    </div>
  </div>
  </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-info">Save Key</button>
    </div>
  </div>
  </fieldset>
</form>