<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Keynote API</title>
</head>
<body>
  <h2>An error occurred!</h2>
  <h4><?php echo $this->message ?></h4>

  <?php if ('development' == APPLICATION_ENV): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), 1) ?>
  </pre>
  
  <?php endif ?>
  
</body>
</html>