<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Keynote API</title>
</head>
<body>
    <div class="alert alert-error">
        <h4>An error occurred!</h4>
        <?php echo $this->message ?>
    </div>

    <?php if ('development' == APPLICATION_ENV): ?>
    <div class="alert alert-block">
        <h4>Exception information:</h4>
        <b>Message:</b>
        <?php echo $this->exception->getMessage() ?>
    </div>

    <div class="alert alert-block alert-info">
        <h4>Stack trace:</h4>
        <pre><?php echo $this->exception->getTraceAsString() ?></pre>
    </div>

    <div class="alert alert-block alert-info">
       <h4>Request Parameters:</h4>
       <pre><?php echo var_export($this->request->getParams(), 1) ?></pre>
       <?php endif ?>
    </div>

</body>
</html>
