<?php
$view = $this->url(array('controller' => 'abc', 'action' => 'generate'));
$send = $this->url(array('controller' => 'abc', 'action' => 'sendmail'));
?>
<form class="form" method="post" action="/abc/generate">
  <fieldset>
    <legend>Automatic Brick Creator</legend>

    <div class="alert alert-info">
    <strong>NOTE!</strong> Complete the form in full remembering to select the correct slot, no. of days, interval, mail subject etc.  Always view the brick before sending to ensure all looks OK!
    </div>

    <legend>Contact &amp; Prospect Details</legend>

    <div class="row-fluid">
      <div class="span4">
        <label for="fullName">Your Full Name</label>
        <input type="text" id="fullName" name="fullName" placeholder="Your Full Name" required>
      </div>    
      <div class="span4">
        <label for="mailFrom">Your E-Mail</label>
        <input type="text" id="mailFrom" name="mailFrom" placeholder="someone@keynote.com" required>
      </div>
      <div class="span4">
        <label for="ccAddress">CC</label>
        <input type="text" id="ccAddress" name="ccAddress" placeholder="somebodyelse@example.com">
      </div>    
    </div>
    
    <div class="row-fluid">  
      <div class="span4">
        <label for="prospectName">Prospect Name</label>
        <input type="text" id="prospectName" name="prospectName" placeholder="Prospect Name" required>
      </div>    
      <div class="span8">
        <label for="mailTo">Prospect E-Mail</label>
        <input type="text" id="mailTo" name="mailTo" placeholder="someone@example.com" required>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span12">
        <label for="mailSubject">Mail Subject</label>
        <input class="span6" type="text" id="mailSubject" name="mailSubject" value="Keynote - Your site performance is being impacted" required>
      </div>
    </div>

    <legend>Brick Details</legend>

    <div class="row-fluid">
      <div class="span4">
        <label for="url">URL Monitored</label>
        <input type="text" id="url" name="url" placeholder="www.example.com" required>
      </div>    
      <div class="span4">
        <label for="slotId">Slot ID</label>
        <select id="slotId" name="slotId" placeholder="Slot ID">
          <?php foreach($this->slotIds as $alias => $sid): ?>
          <option value="<?php echo $sid[0] ?>,<?php echo $sid[1] ?>"><?php echo $alias ?></option>
          <?php endforeach; ?>
        </select>
      </div>    
      <div class="span4">
        <label for="am">Averaging Method</label>
        <select id="am" name="am">
          <option value="AM">Arithmetric Mean</option>
          <option value="GM" selected>Geometric Mean</option>
        </select>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span4">
        <label for="days">No. of Days</label>
        <select id="days" name="days">
          <option value="86400">1 Day</option>
          <option value="172800">2 Day</option>
          <option value="259200">3 Day</option>
          <option value="345600">4 Day</option>
          <option value="432000">5 Day</option>
          <option value="604800" selected>1 Week</option>
        </select>
      </div>
      <div class="span4">
        <label for="interval">Interval</label>
        <select id="interval" name="interval">
          <option value="5">5 minute</option>
          <option value="15" selected>15 minute</option>
          <option value="30">30 minute</option>
          <option value="60">60 minute</option>
        </select>
      </div>
      <div class="span4">
        <label for="browserDevice">Browser/Device</label>
        <input type="text" id="browserDevice" name="browserDevice" placeholder="e.g. IE 9, iPhone 5" required>
      </div>
    </div>
    
    <div class="row-fluid">
      <div class="span4">
        <label for="customHeadline">Custom Headline</label>
        <input type="text" id="customHeadline" name="customHeadline" placeholder="Optional Headline">
      </div>
      <div class="span8">
        <label for="customMessage">Custom Message</label>
        <textarea class="span8" rows="2" id="customMessage" name="customMessage" placeholder="Optional Message"></textarea>
      </div>
    </div>
	
	<div class="row-fluid">
        <button type="submit" class="btn btn-info" onclick="this.form.action='<?php echo $view ?>'"><i class="icon-white icon-eye-open"></i> View Brick</button>
        <button type="submit" class="btn btn-success" onclick="this.form.action='<?php echo $send ?>'"><i class="icon-white icon-envelope"></i> Send Brick</button>
    </div>
        
  </fieldset>
</form>