  <!-- Example row of columns -->
  <div class="row" id="sortable2">

    <div class="span3">
      <div class="widget ui-state-default">
        <div class="widget-header">
          <div class="widget-title"><i class="icon-time icon-white"></i> Clock</div>
        </div>
        <div class="widget-body">
           <div id="Date"></div>
           <ul id="cdate">
             <li id="hours"></li>
             <li id="point">:</li>
             <li id="min"></li>
             <li id="sec"></li>
           </ul>
        </div>
      </div>
      <script>wClock()</script>
    </div>

    <div class="span3">
      <div class="widget ui-state-default">
        <div class="widget-header">
          <div class="widget-title"><i class="icon-time icon-white"></i> Fastest Measurement</div>
        </div>
        <div class="widget-body" id="widget-id-1">
          <h5 class="alias"></h5>
          <div class="t-size-x60 perf"></div>
          <h5 class="sub-info"></h5>
          <div class="t-size-x30 previous"><span class="loading">Widget Loading ...</span></div>
	      <script>getData(1, 'fastest');</script>
        </div>
      </div>
    </div>

    <div class="span3">
      <div class="widget ui-state-default">
        <div class="widget-header">
          <div class="widget-title"><i class="icon-time icon-white"></i> Slowest Measurement</div>
        </div>
        <div class="widget-body" id="widget-id-2">
          <h5 class="alias"></h5>
          <div class="t-size-x60 perf"></div>
          <h5 class="sub-info"></h5>
          <div class="t-size-x30 previous"><span class="loading">Widget Loading ...</span></div>
          <script>getData(2, 'slowest');</script>
        </div>
      </div>
    </div>


    <div class="span3">
      <div class="widget ui-state-default">
        <div class="widget-header">
          <div class="widget-title"><i class="icon-time icon-white"></i> Lowest Availability</div>
        </div>
        <div class="widget-body" id="widget-id-3">
          <h5 class="alias"></h5>
          <div class="t-size-x60 perf"></div>
          <h5 class="sub-info"></h5>
          <div class="t-size-x30 previous"><span class="loading">Widget Loading ...</span></div>
	    <script>getData(3, 'avail');</script>
        </div>
      </div>
    </div>

    </div>

          <!-- Example row of columns -->
    <div class="row" id="sortable3">

    <div class="span3">
      <div class="widget ui-state-default">
        <div class="widget-header">
          <div class="widget-title graph-title" id="smChart"><i class="icon-signal icon-white"></i> Random Graph</div>
        </div>
        <div class="widget-body">
          <div id="smallChart" style="width: 100%; height: 150px;">Chart Loading ...</div>
        </div>
      </div>
      <script>createGraph(smallChart, 'smChart', <?php //echo $this->slotId?>'')</script>
    </div>

    <div class="span3">
      <div class="widget ui-state-default">
        <div class="widget-header">
          <div class="widget-title"><i class="icon-time icon-white"></i> Random Measurement</div>
        </div>
        <div class="widget-body" id="widget-id-5">
          <h5 class="alias"></h5>
          <div class="t-size-x60 perf"></div>
          <h5 class="sub-info"></h5>
          <div class="t-size-x30 previous"><span class="loading">Widget Loading ...</span></div>
          <script>getData(5, 'random');</script>
        </div>
      </div>
    </div>

    <div class="span3">
      <div class="widget ui-state-default">
        <div class="widget-header">
          <div class="widget-title"><i class="icon-globe icon-white"></i>Spare Widget</div>
        </div>
        <div class="widget-body">
        </div>
      </div>
    </div>

    <div class="span3">
      <div class="widget ui-state-default">
        <div class="widget-header">
          <div class="widget-title"><i class="icon-time icon-white"></i> Random Measurement</div>
        </div>
        <div class="widget-body" id="widget-id-7">
          <h5 class="alias"></h5>
          <div class="t-size-x60 perf"></div>
          <h5 class="sub-info"></h5>
          <div class="t-size-x30 previous"><span class="loading">Widget Loading ...</span></div>
          <script>getData(7, 'random');</script>
        </div>
      </div>
    </div>

    </div>

    <div class="row">

    <div class="span12">
      <div class="widget">
        <div class="widget-header">
          <div class="widget-title graph-title" id="randomChart"><i class="icon-signal icon-white"></i> Random Graph</div>
        </div>
        <div class="widget-body">
          <div id="rndChart" style="width: 100%; height: 150px;">Chart Loading ...</div>
        </div>
      </div>
      <script>createGraph(rndChart, 'randomChart', '')</script>
    </div>

    </div>


<script>
$(function() {
    $( "#sortable" ).sortable({
        handle: '.widget-header',
        cursor: 'move',
        revert: true
    });
    $( "#sortable2" ).sortable({
        handle: '.widget-header',
        cursor: 'move',
        revert: true
    });
    $( "#sortable3" ).sortable({
        handle: '.widget-header',
        cursor: 'move',
        revert: true
    });

    $("div").disableSelection();
});
</script>
