
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dashboard">
  <thead>
    <tr>
      <th>Measurement</th>
      <th width="75">5 min</th>
      <th width="75">15 min</th>
      <th width="75">1 hour</th>
      <th width="75">24 hours</th>
      <th width="75">5 min</th>
      <th width="75">15 min</th>
      <th width="75">1 hour</th>
      <th width="75">24 hours</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
<script>
    $(document).ready(function() {
    	$('#dashboard').dataTable({
    	    "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
    	    "sPaginationType": "bootstrap",
    	    "oLanguage": {
    	      "sLengthMenu": "_MENU_ records per page"
    	    },
    		"sAjaxSource": "/dashboard/tabledata"
    	});
    });

    $('#dashboard').tooltip({
        selector: "button[rel=tooltip]"
    });
</script>
