
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dashboard">
  <thead>
    <tr>
      <th>Measurement</th>
      <th width="75">5 min</th>
      <th width="75">15 min</th>
      <th width="75">1 hour</th>
      <th width="75">24 hours</th>
      <th width="75">5 min</th>
      <th width="75">15 min</th>
      <th width="75">1 hour</th>
      <th width="75">24 hours</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

