<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Keynote API</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="/images/favicon.ico">
    <link href="/css/style.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
  </head>
  <body>
    <?php echo $this->render('navbar.phtml') ?>

    <!-- Container -->
    <div class="container">

      <?php echo $this->layout()->content ?>

      <hr class="featurette-divider">

      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; Keynote Systems, Inc. 2013</p>
      </footer>

      <!-- Modal Window -->
      <div id="example" class="modal hide fade in" style="display: none; ">
        <form id="modal-form" action="/save" data-remote="true" method="post">
          <div class="modal-header">
            <a class="close" data-dismiss="modal">x</a>
            <h3>Enter new API Key</h3>
          </div>
          <div class="modal-body">
            <input class="input-xlarge" type="text" name="api_key" placeholder="API KEY">
          </div>
          <div class="modal-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            <a href="#" class="btn" data-dismiss="modal">Close</a>
          </div>
        </form>
      </div>
      <!-- End Modal -->

    </div> <!-- /container -->
  </body>
</html>
