<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Keynote - Daily Report</title>
<style type="text/css">
body,html {
	font-size: 100%;
    font-family: 'Gill Sans', Tahoma, sans-serif;
}

table {
    font-size: 80%;
}

h1,
h2,
h3,
h4,
h5,
h6 {
  margin: 10px 0;
  font-family: 'Gill Sans', Tahoma, sans-serif;
  font-weight: bold;
  line-height: 20px;
  color: inherit;
}

h1,
h2,
h3 {
  line-height: 40px;
}

h1 {
  font-size: 38.5px;
}

h2 {
  font-size: 31.5px;
}

h3 {
  font-size: 20.5px;
}

h4 {
  font-size: 15.5px;
}

h5 {
  font-size: 12px;
}

h6 {
  font-size: 11.9px;
}

th {
	background-color: #F9F9F9;
}

#container {
border: 1px solid #DDDDDD;
}
</style>
</head>
<body>
<?php echo $this->layout()->content ?>

<h4>Performance</h4>
<p>Average time for full page(s) download.  Data is compared to last 28 days of history</p>
<table cellpadding="5">
<tr bgcolor="#FFFF99">
<td width="150">Yellow</td><td>15% - 25% above last 28 days</td>
</tr>
<tr bgcolor="#FF9999">
<td>Red</td><td>&gt;25% above last 28 days</td>
</tr>
</table>
<h4>Availability</h4>
<p>Average percentage of successful measurements during the period</p>
<table cellpadding="5">
<tr bgcolor="#FFFF99">
<td width="150">Yellow</td><td>&lt;<?php echo $this->avail_warn ?>%</td>
</tr>
<tr bgcolor="#FF9999">
<td>Red</td><td>&gt;<?php echo $this->avail_crit ?>%</td>
</tr>
</table>
<h4>Objects</h4>
<p>Average Objects downloaded.  Data is compared to last 28 days of history</p>
<table cellpadding="5">
<tr bgcolor="#FFFF99">
<td width="150">Yellow</td><td>15% - 25% above last 28 days</td>
</tr>
<tr bgcolor="#FF9999">
<td>Red</td><td>&gt;25% above last 28 days</td>
</tr>
</table>
<h4>Bytes Downloaded</h4>
<p>Average bytes downloaded.  Data is compared to last 28 days of history</p>
<table cellpadding="5">
<tr bgcolor="#FFFF99">
<td width="150">Yellow</td><td>15% - 25% above last 28 days</td>
</tr>
<tr bgcolor="#FF9999">
<td>Red</td><td>&gt;25% above last 28 days</td>
</tr>
</table>
</body>
</html>
