<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Keynote API</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<!-- Bootstrap -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link rel="shortcut icon" href="/images/favicon.ico">
<link href="/css/style.css" rel="stylesheet">
<style type="text/css">
body {
  padding-top: 60px;
  padding-bottom: 40px;
}

.statusBlack {
  background-color: #00ff00;
}
</style>
<link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
<link href="/css/datatables.css" rel="stylesheet">
</head>
<body>
<?php echo $this->render('navbar.phtml') ?>
  <!-- Container -->
  <div class="container">
  <?php echo $this->layout()->content ?>
    <hr class="featurette-divider">
    <footer>
      <p class="pull-right">
        <a href="#">Back to top</a>
      </p>
      <p>&copy; Keynote Systems, Inc. 2013</p>
    </footer>
  </div>
  <!-- /container -->
  <script src="/js/jquery-latest.min.js"></script>
  <script src="/js/jquery.dataTables.min.js"></script>
  <script src="/bootstrap/js/bootstrap.min.js"></script>
  <script src="/js/datatables.js"></script>
  <script>
  jQuery.extend( jQuery.fn.dataTableExt.oSort, {
	    "num-html-pre": function ( a ) {
	        var x = (a == "-") ? 0 : String(a).replace( /<[\s\S]*?>/g, "" );
	        return parseFloat( x );
	    },

	    "num-html-asc": function ( a, b ) {
	        return ((a < b) ? -1 : ((a > b) ? 1 : 0));
	    },

	    "num-html-desc": function ( a, b ) {
	        return ((a < b) ? 1 : ((a > b) ? -1 : 0));
	    }
	} );
  $(document).ready(function () {
	  //$('#dataTable').html( '<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dashboard">' );
      $('#dashboard').dataTable({
          "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
          "sPaginationType": "bootstrap",
          "oLanguage": {
              "sLengthMenu": "_MENU_ records per page"
          },
          "sAjaxSource": "/dashboard/tabledata",
          "aoColumnDefs": [{
                  "aTargets": [0],
                  "sTitle": "Alias"
              }, {
                  "aTargets": [1],
                  "sTitle": "5min",
                  "sWidth": "75",
                  "sType" : "num-html"
              }, {
                  "aTargets": [2],
                  "sTitle": "15min",
                  "sWidth": "75",
                  "sType" : "num-html"
              }, {
                  "aTargets": [3],
                  "sTitle": "1hr",
                  "sWidth": "75",
                  "sType" : "num-html"
              }, {
                  "aTargets": [4],
                  "sTitle": "24hrs",
                  "sWidth": "75",
                  "sType" : "num-html"
              }, {
                  "aTargets": [5],
                  "sTitle": "5min",
                  "sWidth": "75",
                  "sType" : "num-html"
              }, {
                  "aTargets": [6],
                  "sTitle": "15min",
                  "sWidth": "75",
                  "sType" : "num-html"
              }, {
                  "aTargets": [7],
                  "sTitle": "1hr",
                  "sWidth": "75",
                  "sType" : "num-html"
              }, {
                  "aTargets": [8],
                  "sTitle": "24hrs",
                  "sWidth": "75",
                  "sType" : "num-html"
              }

          ]

      });
  });

  $('#dashboard').tooltip({
      selector: "button[rel=tooltip]"
  });
    </script>
</body>
</html>
