<div class="hero-unit">
  <h1>API Showcase</h1>
  <p>This application showcases various aspects of the Keynote API!</p>
</div>
<form class="form-horizontal" method="post" action="<?php echo $this->baseUrl() ?>/save">
 <fieldset>
    <legend>Enter API Key</legend>

    <div class="control-group">
      <label class="control-label" for="api_key">New API Key</label>
      <div class="controls">
        <input type="text" class="input-xlarge" id="api_key" name="api_key" placeholder="" required>
        <span class="help-block">The current API Key will be used in each showcase application.</span>
        <span class="help-block">To change the key enter a new one and click Update Key.</span>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="api_key">Current API Key</label>
      <div class="controls controls-row">
        <span class="input-xlarge uneditable-input"><?php echo $this->api_key ?></span>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <?php if ($this->api_key): ?>
        <button type="submit" class="btn btn-info">Update Key</button>
        <?php else: ?>
        <button type="submit" class="btn btn-info">Save Key</button>
        <?php endif; ?>
      </div>
    </div>

  </fieldset>
</form>